input:
  model_name_or_path: "saves/qwen2_5vl-7b/single_step_dpo_model"
  source_dataset_path: "data/opensource_data/grounding_r1_aria_transfer.jsonl"

output_data_dir:
  synthetic_data_dir: "data/synthetic_data"
  train_data_dir: "data/llamafactory_training_data"

generation:
  batch_size: 16
  max_samples: 1000
  max_pixels: 2408448
  max_tokens: 4096
  temperature: 0.7
  top_p: 0.8
  smart_image_dir: "cache/multi_step_sft_crop_resize_image"  ###这个东西是保存resize_raw图片，考研换成一样的路径，减少消耗
  passN: 3
  max_roll: 3

  max_num: 2000

process:
  max_pixels: 2408448
  max_workers: 40 
  DOUBLE_CROP_RATE: 0.3
