input:
  model_name_or_path: "saves/qwen2_5vl-7b/multi_step_sft_model"
  source_dataset_path: "data/opensource_data/grounding_r1_aria_transfer.jsonl"

output_data_dir:
  synthetic_data_dir: "data/synthetic_data"
  train_data_dir: "data/llamafactory_training_data"

generation:
  batch_size: 8
  max_samples: 1000
  max_pixels: 2408448
  max_tokens: 4096
  temperature: 0.7
  top_p: 0.8
  smart_image_dir: "cache/multi_step_dpo_crop_resize_image"
  passN: 5
  max_roll: 3
  max_num: 3000

process:
  max_pixels: 802816
  max_workers: 40 
  iou_rate: 0.8
    
